function [fitresult, gof] = createFit(T, f, SmoothParam)
%CREATEFIT(T,F)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : T
%      Y Output: f
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Mar-2021 16:49:17


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( T, f );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = SmoothParam;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'f vs. T', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'T', 'Interpreter', 'none' );
ylabel( 'f', 'Interpreter', 'none' );
grid on


